### ISSUE TITLE
Adding ATHENS_STORAGE_TYPE as Env variable doesn't override the default disk

### ISSUE THREAD

**Issue by salehparsa** [gomods/athens-charts#101]
I've noticed that if you add `ATHENS_STORAGE_TYPE` as an `ENV` variable it will just cause having dupplicated `ATHENS_STORAGE_TYPE` and `disk` always stays. For instance the only way to configure `S3` as a storage is adding following to the values:

```
storage:
  type: s3
  s3:
    region: "MY REGION"
    bucket: "MY BUCKET"
    useDefaultConfiguration: "true"
```
