### ISSUE TITLE
Invalid SSH Git Server secret manifest

### ISSUE THREAD

**Issue by hilariocoelho** [gomods/athens-charts#53]
After version v0.6.0 the chart contains an error when trying to create a SSH Git Server secret.

```
$ helm upgrade athens -n athens athens/athens-proxy --values values.yaml --version 0.9.1
W0111 01:22:20.540470  925927 warnings.go:70] unknown field "data:id_rsa-sample.server.com"
```

```
kind: Secret
apiVersion: v1
metadata:
  name: athens-athens-proxy-ssh-git-servers
  labels:
    
    app: athens-athens-proxy
    chart: athens-proxy-0.9.1
    release: "athens"
    heritage: "Helm"
    app.kubernetes.io/name: athens-athens-proxy
    helm.sh/chart: athens-proxy-0.9.1
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "athens"
    app.kubernetes.io/version: "v0.13.1"
type: Opaque
data:id_rsa-sample.server.com: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KUkVEQUNURUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg=="
```

This is due to the dashes trimming whitespaces/breaklines before and after the `if` introduced [here](https://github.com/gomods/athens-charts/blob/8814fe89986cb5a428f2b1249f852b1094ae4e81/charts/athens-proxy/templates/secret-ssh-git-servers.yaml#L9) 

Removing the dashes everything works properly.
